import "@measured/puck/puck.css";
import "../styles/tailwind.css";

import type { Metadata } from "next";
import {
  PT_Sans as FontHeading,
  Public_Sans as FontSans,
} from "next/font/google";
import { cn } from "./lib/utils";

const fontHeading = FontHeading({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400", "700"],
});
const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans text-[#22272B] antialiased",
          fontSans.variable,
          fontHeading.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
